### ISSUE TITLE
Opinion on using Black as formatter

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#190]
What are your thoughts on doing a 1-time Black reformat and enabling it on push/pull requests? Totally OK if you’re a “no” on this.

There are ways it reformats that I’m not a huge fan of, but I see the wisdom in ways it helps reduce diffs and eliminates time thinking about formatting. I can write something, click “reformat with black” and just focus on the Python code.

Let me know, wanted to get a definitive answer and I’ll cross this one off my list.

to enable (per https://black.readthedocs.io/en/stable/integrations/github_actions.html)

Create a file named .github/workflows/black.yml inside your repository with:

```
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
```
